apiVersion: apps/v1
kind: Deployment
metadata:
  name: __APP_NAME__
spec:
  selector:
    matchLabels:
      run: __APP_NAME__
  replicas: 1
  template:
    metadata:
      labels:
        run: __APP_NAME__
    spec:
      containers:
      - name: __APP_NAME__
        image: __IMAGE__
        ports:
        - containerPort: 4200
---
apiVersion: v1
kind: Service
metadata:
  name: __APP_NAME__
  labels:
    run: __APP_NAME__
spec:
  ports:
  - port: 4200
    protocol: TCP
    targetPort: 4200
  type: LoadBalancer
  selector:
    run: __APP_NAME__
